# https://docs.gitlab.com/ce/ci/yaml

cache:
  key: ${CI_COMMIT_REF_NAME}-cache
  paths:
    - README.html
    - public

render:
  image: conoria/alpine-pandoc
  stage: build
  before_script:
    - apk update
    - apk add make
  script:
    - make
  artifacts:
    paths:
      - README.html

pages:
  image: alpine:3.1
  stage: deploy
  script:
    - mkdir -p public
    - cp -p README.html public/index.html
  artifacts:
    paths:
      - public
