pages:
  image: frankhjung/pandoc:latest
  stage: deploy
  script:
    - make
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
      - /^feature\/*/
    changes:
      - quickcheck.md
